name: Generate priority_proxy.yaml

# 当 priority_proxy.list 文件有变更时触发
on:
  push:
    paths:
      - 'priority_proxy.list'
      - 'priority_direct.list'

jobs:
  update-format:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Update priority_proxy.list format
        run: |
          awk 'BEGIN { print "payload:" } NF { print "  - "$0 }' priority_proxy.list > temp && mv temp priority_proxy.list

      - name: Update priority_direct.list format
        run: |
          awk 'BEGIN { print "payload:" } NF { print "  - "$0 }' priority_direct.list > temp && mv temp priority_direct.list

  
      - name: Push changes
        run: |
          git config --global user.name 'foreverzeus'
          git config --global user.email 'foreverzeus@qq.com'
          git add .
          git commit -m "auto gen .yaml"
          git push https://x-access-token:${{ secrets.work_flow }}@github.com/${{ github.repository }} HEAD:main